R CMD SHLIB plusTwoCpp.cpp
R CMD SHLIB cube.cpp
R CMD SHLIB isEqual.cpp
R CMD SHLIB divideBy3.cpp
R CMD SHLIB fact.cpp
R CMD SHLIB minval.cpp
R CMD SHLIB squareVec.cpp
R CMD SHLIB arrayClass.cpp
#R CMD SHLIB median.cpp
